BEGIN;
-- =========================================================
-- DATABASE SCHEMA FOR singgahdulu.jastip (SUPABASE POSTGRESQL)
-- Salin dan jalankan script ini pada Supabase -> SQL Editor
-- =========================================================

-- 1. TABEL SETTINGS
CREATE TABLE IF NOT EXISTS public.settings (
    id SERIAL PRIMARY KEY,
    store_name TEXT NOT NULL DEFAULT 'singgahdulu.jastip',
    ig TEXT DEFAULT '@singgahdulu.jastip',
    wa TEXT DEFAULT '0812-3456-7890',
    address TEXT DEFAULT 'Jl. Pancasila No. 12, Salatiga (Dekat Lapangan)',
    logo_url TEXT DEFAULT '',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Seed Data Settings
INSERT INTO public.settings (id, store_name, ig, wa, address, logo_url)
VALUES (1, 'singgahdulu.jastip', '@singgahdulu.jastip', '0812-3456-7890', 'Jl. Pancasila No. 12, Salatiga (Dekat Lapangan)', '')
ON CONFLICT (id) DO NOTHING;


-- 2. TABEL BATCHES
CREATE TABLE IF NOT EXISTS public.batches (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    route TEXT NOT NULL,
    cutoff_date DATE,
    arrival_date DATE,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);




-- 3. TABEL ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
    id TEXT PRIMARY KEY,
    batch_id TEXT REFERENCES public.batches(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    customer TEXT NOT NULL,
    phone TEXT,
    item TEXT NOT NULL,
    store TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    fee NUMERIC NOT NULL DEFAULT 0,
    qty INT NOT NULL DEFAULT 1,
    pay_status TEXT NOT NULL DEFAULT 'LUNAS',
    dp_amount NUMERIC DEFAULT 0,
    item_status TEXT NOT NULL DEFAULT 'PENDING',
    buyer TEXT NOT NULL DEFAULT 'Umay',
    pickup TEXT NOT NULL DEFAULT 'Self Pick-up',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);




-- 4. TABEL EXPENSES
CREATE TABLE IF NOT EXISTS public.expenses (
    id TEXT PRIMARY KEY,
    batch_id TEXT REFERENCES public.batches(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    category TEXT NOT NULL,
    amount NUMERIC NOT NULL DEFAULT 0,
    note TEXT,
    paid_by TEXT NOT NULL DEFAULT 'Adhit',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);




-- 5. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;


-- 6. PROFIL PENGGUNA, ROLE, DAN PELUNASAN TALANGAN
-- Akun/password dikelola oleh Supabase Authentication (auth.users).
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.settlements (
    id TEXT PRIMARY KEY,
    batch_id TEXT NOT NULL REFERENCES public.batches(id) ON DELETE CASCADE,
    partner TEXT NOT NULL CHECK (partner IN ('Umay', 'Adhit')),
    amount NUMERIC NOT NULL CHECK (amount > 0),
    source TEXT NOT NULL DEFAULT 'Kas Jastip',
    note TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settlements ENABLE ROW LEVEL SECURITY;

-- Izinkan backfill profil dalam transaksi sebelum normalisasi username di akhir.
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='profiles' AND column_name='username') THEN
  ALTER TABLE public.profiles ALTER COLUMN username DROP NOT NULL;
 END IF;
END $$;

-- Master role: pengguna menyimpan foreign key, bukan nama role.
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
INSERT INTO public.roles (name) VALUES ('admin'), ('koordinator'), ('driver')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES public.roles(id);

-- Pertahankan role pengguna lama; jangan diam-diam menurunkan role yang tidak dikenal.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'role') THEN
        EXECUTE 'UPDATE public.profiles p SET role_id = r.id FROM public.roles r WHERE p.role = r.name AND p.role_id IS NULL';
        IF EXISTS (SELECT 1 FROM public.profiles WHERE role_id IS NULL) THEN
            RAISE EXCEPTION 'Ada role lama yang tidak dikenal. Tambahkan mapping ke public.roles sebelum migrasi.';
        END IF;
    ELSE
        UPDATE public.profiles SET role_id = (SELECT id FROM public.roles WHERE name = 'driver') WHERE role_id IS NULL;
    END IF;
END $$;
ALTER TABLE public.profiles ALTER COLUMN role_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS profiles_role_id_idx ON public.profiles(role_id);

CREATE OR REPLACE FUNCTION public.current_app_role()
RETURNS TEXT LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = ''
AS $$
    SELECT r.name FROM public.profiles p
    JOIN public.roles r ON r.id = p.role_id
    WHERE p.id = (SELECT auth.uid())
$$;
REVOKE ALL ON FUNCTION public.current_app_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_role() TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, name, role_id)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', NEW.email, 'Pengguna'),
            (SELECT id FROM public.roles WHERE name = 'driver'))
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Tidak memakai CASCADE: dependency custom harus ditinjau, bukan ikut dihapus.
ALTER TABLE public.profiles DROP COLUMN IF EXISTS role;
INSERT INTO public.profiles (id, name, role_id)
SELECT id, COALESCE(raw_user_meta_data->>'name', email, 'Pengguna'),
       (SELECT id FROM public.roles WHERE name = 'driver')
FROM auth.users ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.roles FROM anon, authenticated;
GRANT SELECT ON public.roles TO authenticated;
DROP POLICY IF EXISTS roles_read ON public.roles;
CREATE POLICY roles_read ON public.roles FOR SELECT TO authenticated USING (true);

-- Hapus policy versi lama maupun versi script ini agar bisa dijalankan ulang.
DO $$
DECLARE p record;
BEGIN
  FOR p IN SELECT schemaname, tablename, policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN ('profiles','settings','batches','orders','expenses','settlements')
  LOOP
    EXECUTE format('DROP POLICY %I ON %I.%I', p.policyname, p.schemaname, p.tablename);
  END LOOP;
END $$;

REVOKE ALL ON public.profiles, public.settings, public.batches, public.orders, public.expenses, public.settlements FROM anon;
GRANT SELECT ON public.profiles TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON public.profiles FROM authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.settings, public.batches, public.orders, public.expenses, public.settlements TO authenticated;

CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated
USING (id = (SELECT auth.uid()) OR public.current_app_role() = 'admin');

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['settings','batches','orders','expenses','settlements'] LOOP
    EXECUTE format('CREATE POLICY member_read ON public.%I FOR SELECT TO authenticated USING (public.current_app_role() IN (''admin'', ''koordinator'', ''driver''))', t);
  END LOOP;
  FOREACH t IN ARRAY ARRAY['batches','orders','expenses'] LOOP
    EXECUTE format('CREATE POLICY operator_write ON public.%I FOR ALL TO authenticated USING (public.current_app_role() IN (''admin'', ''koordinator'')) WITH CHECK (public.current_app_role() IN (''admin'', ''koordinator''))', t);
  END LOOP;
END $$;
CREATE POLICY admin_settings ON public.settings FOR ALL TO authenticated
USING (public.current_app_role() = 'admin') WITH CHECK (public.current_app_role() = 'admin');
CREATE POLICY operator_settlements ON public.settlements FOR INSERT TO authenticated
WITH CHECK (public.current_app_role() IN ('admin','koordinator') AND created_by = (SELECT auth.uid()));

CREATE INDEX IF NOT EXISTS orders_batch_idx ON public.orders(batch_id);
CREATE INDEX IF NOT EXISTS expenses_batch_idx ON public.expenses(batch_id);
CREATE INDEX IF NOT EXISTS settlements_batch_idx ON public.settlements(batch_id);

-- Jalankan setelah migrasi normalize_roles.
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT;
UPDATE public.profiles p SET username =
    CASE WHEN u.email ~ '^[a-z0-9_]{3,40}@users[.]singgahdulu[.]invalid$'
         THEN split_part(u.email, '@', 1)
         ELSE 'user_' || replace(p.id::text, '-', '') END
FROM auth.users u WHERE p.id = u.id AND p.username IS NULL;
ALTER TABLE public.profiles ALTER COLUMN username SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS profiles_username_unique ON public.profiles(username);
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.profiles'::regclass AND conname = 'profiles_username_format') THEN
        ALTER TABLE public.profiles ADD CONSTRAINT profiles_username_format CHECK (username ~ '^[a-z0-9_]{3,40}$');
    END IF;
END $$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, name, username, role_id)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', 'Pengguna'),
        CASE WHEN NEW.email ~ '^[a-z0-9_]{3,40}@users[.]singgahdulu[.]invalid$'
             THEN split_part(NEW.email, '@', 1)
             ELSE 'user_' || replace(NEW.id::text, '-', '') END,
        (SELECT id FROM public.roles WHERE name = 'driver'))
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
NOTIFY pgrst, 'reload schema';

COMMIT;
