-- Untuk database yang sudah menjalankan supabase_schema.sql versi role TEXT.
BEGIN;

-- Master role: pengguna menyimpan foreign key, bukan nama role.
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);
INSERT INTO public.roles (name) VALUES ('admin'), ('koordinator'), ('driver')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES public.roles(id);

-- Pertahankan role pengguna lama; jangan diam-diam menurunkan role yang tidak dikenal.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'role') THEN
        EXECUTE 'UPDATE public.profiles p SET role_id = r.id FROM public.roles r WHERE p.role = r.name AND p.role_id IS NULL';
        IF EXISTS (SELECT 1 FROM public.profiles WHERE role_id IS NULL) THEN
            RAISE EXCEPTION 'Ada role lama yang tidak dikenal. Tambahkan mapping ke public.roles sebelum migrasi.';
        END IF;
    ELSE
        UPDATE public.profiles SET role_id = (SELECT id FROM public.roles WHERE name = 'driver') WHERE role_id IS NULL;
    END IF;
END $$;
ALTER TABLE public.profiles ALTER COLUMN role_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS profiles_role_id_idx ON public.profiles(role_id);

CREATE OR REPLACE FUNCTION public.current_app_role()
RETURNS TEXT LANGUAGE SQL STABLE SECURITY DEFINER SET search_path = ''
AS $$
    SELECT r.name FROM public.profiles p
    JOIN public.roles r ON r.id = p.role_id
    WHERE p.id = (SELECT auth.uid())
$$;
REVOKE ALL ON FUNCTION public.current_app_role() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_role() TO authenticated;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.profiles (id, name, role_id)
    VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'name', NEW.email, 'Pengguna'),
            (SELECT id FROM public.roles WHERE name = 'driver'))
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Tidak memakai CASCADE: dependency custom harus ditinjau, bukan ikut dihapus.
ALTER TABLE public.profiles DROP COLUMN IF EXISTS role;
INSERT INTO public.profiles (id, name, role_id)
SELECT id, COALESCE(raw_user_meta_data->>'name', email, 'Pengguna'),
       (SELECT id FROM public.roles WHERE name = 'driver')
FROM auth.users ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.roles FROM anon, authenticated;
GRANT SELECT ON public.roles TO authenticated;
DROP POLICY IF EXISTS roles_read ON public.roles;
CREATE POLICY roles_read ON public.roles FOR SELECT TO authenticated USING (true);

NOTIFY pgrst, 'reload schema';
COMMIT;
